version: '3.8'

services:
  qr_code_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - QR_CODE_DIR=/app/qr_codes
      - FILL_COLOR=Red
      - BACK_COLOR=Yellow
    volumes:
      - ./qr_codes:/app/qr_codes  # Maps the local 'qr_codes' directory to '/app/qr_codes' in the container
    command: --url https://github.com/existedmaster/Module-7-QR-Code-Generator # Replace 'main.py' with your script's filename if different
