name: DockerCheck

on: #Triggered on push or pull into main branch#
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test: #Perfoms test job on ubuntu, using the stated steps and steps can be ran with commands#
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build: #Builds and pushes Docker image to Docker Hub#
    runs-on: ubuntu-latest
    needs: test

    services: #Sets up Docker service for building and pushing images#
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_HOST: tcp://localhost:2375

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers #Caches Docker layers to speed up subsequent builds#
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub #Logs into Docker Hub using stored credentials#
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_U }}
          password: ${{ secrets.DOCKP }}

      - name: Build and push Docker image
        run: |
          docker build -t existedmaster/qr_code_generator:latest -f Dockerfile .
          docker push existedmaster/qr_code_generator:latest

      - name: Build and push Docker Compose images
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push